# Generated by Django 5.0.7 on 2024-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_patient_visit_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
