# Generated by Django 5.0.7 on 2024-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_patient_address_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
